apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qmdemo-self-signed
  namespace: mq-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  commonName: qmdemo
  dnsNames:
  - qmdemo.ibm.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: qmdemo-cert
  subject:
    organizations:
    - IBM
