apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: mq-demo
spec:
  commonName: qmdemo
  dnsNames:
  - qmdemo.ibm.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: qmdemo-cert
  subject:
    organizations:
    - IBM
