resources:
- ../../../templates/native-ha

patches:
- path: ./qm.yaml

# Uncomment to include components required for a Prometheus MQ Service, requires a container image with the collector.
#components:
#- ../../../components/prometheus-monitor

generatorOptions:
 disableNameSuffixHash: true

# Add uniform-cluster-wide static MQSC and qm.ini file.
configMapGenerator:
- name: mqsc-configmap
  behavior: merge
  files:
  - static-uc.mqsc
  - dynamic.mqsc

- name: qm-ini-configmap
  behavior: create
  files:
  - qm.ini

# Add the configMap that will be used for dynamic updates, this should be used globally i.e. stay the same in each environment.

- name: dynamic-mqsc-configmap
  behavior: create
  files:
  - dynamic.mqsc
