apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-exit
  namespace: mq-demo
spec:
  steps:
    - computeResources: {}
      image: ubi9
      name: get-exit-step
      script: |
        #!/usr/bin/env bash
        echo "Creating directory"
        mkdir /workspace/output/mq-exit/
        curl http://servername:8000/9.4.2.1-IBM-Instana-MQ-Tracing-LinuxX64.tar.gz --output /workspace/output/mq-exit/9.4.2.1-IBM-Instana-MQ-Tracing-LinuxX64.tar.gz
        tar -xzf /workspace/output/mq-exit/9.4.2.1-IBM-Instana-MQ-Tracing-LinuxX64.tar.gz -C /workspace/output/mq-exit/
        ls -lrt /workspace/output/mq-exit/
  workspaces:
    - name: exit-secret
    - name: output
