apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: mq-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: queue-manager-deployment/queue-managers
    repoURL: 'https://github.com/ibm-messaging/mq-gitops-samples'
    targetRevision: test-with-metrics 
  project: default
