namePrefix: qm04-

resources:
- ../uniform

components:
- ../../../components/versions/dev

transformers:
- sed-transformer.yaml


# Rename the deployment queue manager name, not the actual queue manager, this gets the prefix from above.
patches:
- path: ./qm.yaml
- target:
    group: mq.ibm.com
    kind: QueueManager
  patch: |-
    - op: replace
      path: /metadata/name
      value: qm

