apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: mq-otel-pipeline
  namespace: mq-demo
spec:
  params:
    - default: 9.4.2.0-r1
      description: IBM MQ version
      name: mqVersion
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/mq-with-metrics'
      name: mqSrcImage
      type: string
  tasks:
    - name: git-clone-mq-gitops
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/ibm-messaging/mq-gitops-samples'
        - name: REVISION
          value: otel-tracing
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: mq-workspace
    - name: get-exit
      runAfter:
        - git-clone-mq-gitops
      taskRef:
        kind: Task
        name: get-exit
      workspaces:
        - name: exit-secret
          workspace: exit-secret
        - name: output
          workspace: mq-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/mq-with-otel:v1.0'
        - name: DOCKERFILE
          value: queue-manager-custom-otel/Dockerfile
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--build-arg mqVersion=$(params.mqVersion) --build-arg mqSrcImage=$(params.mqSrcImage)'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - get-exit
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: mq-workspace
        - name: dockerconfig
          workspace: mq-metrics-dockerconfig
  workspaces:
    - name: mq-workspace
    - name: mq-metrics-dockerconfig
    - name: exit-secret
  finally: []