apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
 disableNameSuffixHash: true

resources:
  - ./service.yaml
  - ./service-monitor.yaml

patches:
- path: qm.yaml

- patch: |-
    - op: add
      path: /spec/template/pod/containers/0/ports
      value:
      - containerPort: 9157
        protocol: TCP

  target:
    group: mq.ibm.com
    kind: QueueManager
    