apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: ibm-mq
spec:
  license:
    accept: true
    license: L-CLXQ-ADXTK3
    use: Development
  version: 9.4.2.1-r1
  queueManager:
    image: image-registry.openshift-image-registry.svc:5000/mq-demo/mq-with-otel:9.4.2.1-r1